#!/bin/bash

SERVER_PATH="umpleonline/chatbot/stanford-corenlp-full-2018-10-05/"
#export CORENLP_HOME="*"  # This is not actually used, but must still be defined

cd ${SERVER_PATH}
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer \
    -preload tokenize,ssplit,pos,lemma,ner,parse,depparse \
    -status_port 9000 -port 9000 -timeout 15000 & 
